# Generated by Django 5.2.17 on 2026-09-08 02:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_tracking",
                    models.CharField(
                        help_text="ID interno persistente asignado por el microservicio de visión.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="Alias opcional asignado manualmente (ej. 'Mesero turno tarde').",
                        max_length=100,
                    ),
                ),
                (
                    "primera_deteccion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Personal",
                "verbose_name_plural": "Personal",
                "ordering": ["-primera_deteccion"],
            },
        ),
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        help_text="Número/identificador visible de la mesa (ej. Mesa 5).",
                        unique=True,
                    ),
                ),
                (
                    "camara_id",
                    models.CharField(
                        help_text="Identificador de la cámara de seguridad que cubre esta mesa.",
                        max_length=50,
                    ),
                ),
                (
                    "zona_poligono",
                    models.JSONField(
                        help_text="Lista de puntos [[x1,y1],[x2,y2],...] que definen el polígono fijo de la mesa en el frame de video, usado para el análisis de solapamiento geométrico (overlap) contra las detecciones de YOLOv8."
                    ),
                ),
                ("capacidad", models.PositiveSmallIntegerField(default=4)),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Si está en False, el sistema ignora esta mesa (ej. en mantenimiento).",
                    ),
                ),
                (
                    "mesas_adyacentes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Mesas físicamente contiguas, usadas por la heurística de fusión de mesas (ocupación simultánea de adyacentes + exceso de personas detectadas).",
                        to="monitoreo.mesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesa",
                "verbose_name_plural": "Mesas",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="EventoOcupacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("fin", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_gracia", "En período de gracia"),
                            ("ocupada", "Ocupada"),
                            ("liberada", "Liberada"),
                            ("fusionada", "Fusionada con otra mesa"),
                        ],
                        default="en_gracia",
                        max_length=20,
                    ),
                ),
                (
                    "num_personas_detectadas",
                    models.PositiveSmallIntegerField(default=1),
                ),
                (
                    "confianza_deteccion",
                    models.FloatField(
                        default=0.0,
                        help_text="Confianza promedio de YOLOv8 para las detecciones de esta ocupación.",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "fusionada_con",
                    models.ForeignKey(
                        blank=True,
                        help_text="Otro EventoOcupacion con el que se detectó fusión heurística (mesas adyacentes ocupadas a la vez + exceso de personas).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fusiones_hijas",
                        to="monitoreo.eventoocupacion",
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_ocupacion",
                        to="monitoreo.mesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de ocupación",
                "verbose_name_plural": "Eventos de ocupación",
                "ordering": ["-inicio"],
            },
        ),
        migrations.CreateModel(
            name="EventoEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("aperitivo", "Aperitivo"),
                            ("bebida", "Bebida"),
                            ("plato_principal", "Plato principal"),
                            ("cuenta", "Cuenta"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "tiempo_espera_segundos",
                    models.PositiveIntegerField(
                        help_text="Segundos entre el inicio de la ocupación y esta entrega."
                    ),
                ),
                ("confianza_deteccion", models.FloatField(default=0.0)),
                (
                    "evento_ocupacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="monitoreo.eventoocupacion",
                    ),
                ),
                (
                    "personal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Puede ser null si el sistema no logró asociar a ningún miembro del staff.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entregas",
                        to="monitoreo.personal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de entrega",
                "verbose_name_plural": "Eventos de entrega",
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="eventoocupacion",
            index=models.Index(
                fields=["mesa", "inicio"], name="monitoreo_e_mesa_id_9136f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventoocupacion",
            index=models.Index(fields=["estado"], name="monitoreo_e_estado_5fbccf_idx"),
        ),
        migrations.AddIndex(
            model_name="eventoentrega",
            index=models.Index(
                fields=["evento_ocupacion", "timestamp"],
                name="monitoreo_e_evento__3ed797_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventoentrega",
            index=models.Index(
                fields=["personal"], name="monitoreo_e_persona_a668da_idx"
            ),
        ),
    ]
