# Generated by Django 5.2.17 on 2026-09-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoocupacion',
            name='clip_s3_key',
            field=models.CharField(blank=True, default='', help_text='Key del clip de video subido a S3 como evidencia de esta ocupación (ej. evidencia/cam-1/mesa-3/2026/09/11/ocupacion-20260911T123000.mp4). Lo sube el microservicio de visión al cerrarse la ocupación; vacío si no hay bucket configurado o la subida falló.', max_length=512),
        ),
    ]
